import { ToasterProvider } from '@/providers/taost-provider'
import './globals.css'
import { redirect } from 'next/navigation'
import { ModalProvider } from '@/providers/modal-provider'


export const metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        <ModalProvider />

        {children}</body>
    </html>
  )

}
